-- 코드를 입력하세요

# SELECT USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
# FROM ONLINE_SALE
# WHERE USER_ID IN (SELECT USER_ID 
#                  FROM USER_INFO
#                  WHERE YEAR(JOINED) == 2021)


# SELECT YEAR(JOINED) AS YEAR, MONTH(JOINED) AS MONTH, USER_ID, PRODUCT_ID, SALES_AMOUNT
# FROM (SELECT USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
#         FROM ONLINE_SALE OS
#         WHERE USER_ID IN (SELECT USER_ID 
#                          FROM USER_INFO UI
#                          WHERE YEAR(JOINED) = 2021))

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT OS.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) AS PURCHASED_RATION
FROM USER_INFO UI JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
WHERE YEAR(UI.JOINED) = 2021
GROUP BY MONTH(SALES_DATE)
ORDER BY YEAR, MONTH