-- 코드를 작성해주세요
WITH RECURSIVE CTE(ID, PARENT_ID, n) AS (
    SELECT ID, PARENT_ID, 1 AS n
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
    
    UNION ALL

    SELECT ED.ID, ED.PARENT_ID, CTE.n + 1 AS n
    FROM ECOLI_DATA ED
    INNER JOIN CTE ON CTE.ID = ED.PARENT_ID
    )
    
SELECT COUNT(ID) AS COUNT, n AS GENERATION
FROM CTE
WHERE ID NOT IN (SELECT PARENT_ID
                FROM ECOLI_DATA
                WHERE PARENT_ID IS NOT NULL)       
GROUP BY GENERATION
ORDER BY GENERATION