-- 코드를 작성해주세요

# SELECT CONCAT('/home/grep/src/',UGB.BOARD_ID,'/',UGF.FILE_ID,UGF.FILE_NAME, UGF.FILE_EXT) AS FILE_PATH
# FROM USED_GOODS_BOARD AS UGB JOIN USED_GOODS_FILE AS UGF ON UGB.BOARD_ID = UGF.BOARD_ID
# WHERE UGB.BOARD_ID IN (SELECT BOARD_ID
#                         FROM USED_GOODS_BOARD
#                         ORDER BY VIEWS DESC
#                         LIMIT 1)
# ORDER BY UGF.FILE_ID DESC


SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO FI JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FNI.FISH_NAME IN ('BASS', 'SNAPPER')

